const getters = {
    me: state => state.me,
    isLogin:state => state.isLogin,
    feed: state => state.feed,
    addresses: state => state.addresses,
    coupons: state => state.coupons,
    credits: state => state.credits,
    creditskip: state => state.creditskip,
/*    allPoints: state => state.allPoints,*/
    initialized: state => state.initialized,
    wishlist: state => state.wishlist,
    save: state => state.save,
    orderNotifications: state => state.orderNotifications,
    promotionNotifications: state => state.promotionNotifications,
    otherNotifications: state => state.otherNotifications,
    ticketNotifications: state => state.ticketNotifications,
    orderNewNotifications: state => state.orderNewNotifications,
    newsNotifications: state => state.newsNotifications,
    activityNotificationnoRead: state => state.activityNotificationnoRead,
    promoNotificationnoRead: state => state.promoNotificationnoRead,
    otherNotificationnoRead: state => state.otherNotificationnoRead,
    ticketNotificationnoRead: state => state.ticketNotificationnoRead,
    orderNotificationnoRead: state => state.orderNotificationnoRead,
    newsNotificationnoRead: state => state.newsNotificationnoRead,
    wishProducts: state => state.wishProducts,
    refreshProducts: state => state.refreshProducts,
    wishskip: state => state.wishskip,
    youlikeProducts: state => state.youlikeProducts,
    youlikeskip:state => state.youlikeskip,
    headerImage: state => state.headerImage,
    promotionNtSkip: state => state.promotionNtSkip,
    promotionNtLoaded: state => state.promotionNtLoaded,
    promotionNtFinished: state => state.promotionNtFinished,
    orderNtSkip: state => state.orderNtSkip,
    orderNtLoaded: state => state.orderNtLoaded,
    orderNtFinished: state => state.orderNtFinished,
    otherNtSkip: state => state.otherNtSkip,
    otherNtLoaded: state => state.otherNtLoaded,
    otherNtFinished: state => state.otherNtFinished,
    ticketNtSkip: state => state.ticketNtSkip,
    ticketNtLoaded: state => state.ticketNtLoaded,
    ticketNtFinished: state => state.ticketNtFinished,
    orderNewNtSkip: state => state.orderNewNtSkip,
    orderNewNtLoaded: state => state.orderNewNtLoaded,
    orderNewNtFinished: state => state.orderNewNtFinished,
    newsNtSkip: state => state.newsNtSkip,
    newsNtLoaded: state => state.newsNtLoaded,
    newsNtFinished: state => state.newsNtFinished,
    notificationCount: state => state.notificationCount,
    orderCountProcessing: state => state.orderCountProcessing,
    orderCountShipped: state => state.orderCountShipped,
    orderCountReceipt: state => state.orderCountReceipt,
    orderCountCanceled: state => state.orderCountCanceled,
    orderCountUnpaid: state => state.orderCountUnpaid,
    message: state => state.message,
    creditcards: state =>state.creditcards,
    mercadocreditcards: state => state.mercadocreditcards,
    trackOrder: state => state.trackOrder,
    trackOrderSkip: state => state.trackOrderSkip,

    expiredCoupons:state => state.expiredCoupons,
    expiredCouponsSkip:state => state.expiredCouponsSkip,
    currencyList:state => state.currencyList,
    shoppingCartCount:state => state.shoppingCartCount,
    messageM1518:state => state.messageM1518,
    messageM1521:state => state.messageM1521,
    relationProducts:state => state.relationProducts,
    relationProductsSkip:state => state.relationProductsSkip,

    survey: state => state.survey,

    wishlistEvent:state => state.wishlistEvent,

    hasNoCommentOrder: state => state.hasNoCommentOrder,

    dobulePoints:state => state.dobulePoints
}

export default getters;