/**
 * Created by shao_ on 2017/8/23.
 */


export const ME_HEADER_IMAGE = 'ME_HEADER_IMAGE'

export const ME_INITIALIZED = 'ME_INITIALIZED'
export const ME_GET = 'ME_GET'
export const ME_GET_FEED = 'ME_GET_FEED'
export const ME_GET_ADDRESSES = 'ME_GET_ADDRESSES'
export const ME_MAKE_DEFAULT = 'ME_MAKE_DEFAULT'
export const ME_GET_COUPONS = 'ME_GET_COUPONS'
export const ME_GET_CREDITS = 'ME_GET_CREDITS'
export const ME_GET_CREDITS_SKIP = 'ME_GET_CREDITS_SKIP'
export const ME_GET_YOU_LIKES = 'ME_GET_YOU_LIKES'
export const ME_GET_WISH_LIST = 'ME_GET_WISH_LIST'

export const ME_GET_EXPIRED_COUPONS = 'ME_GET_EXPIRED_COUPONS';
export const ME_GET_EXPIRED_COUPONS_SKIP = 'ME_GET_EXPIRED_COUPONS_SKIP';

export const ME_GET_NOTIFICATIONS_ORDER = 'ME_GET_NOTIFICATIONS_ORDER'
export const ME_GET_NOTIFICATION_O_SKIP = 'ME_GET_NOTIFICATION_O_SKIP'
export const ME_GET_NOTIFICATION_O_LOADED = 'ME_GET_NOTIFICATION_O_LOADED'
export const ME_GET_NOTIFICATION_O_FINISHED = 'ME_GET_NOTIFICATION_O_FINISHED'


export const ME_GET_NOTIFICATIONS_PROMOTION = 'ME_GET_NOTIFICATIONS_PROMOTION'
export const ME_GET_NOTIFICATION_P_SKIP = 'ME_GET_NOTIFICATION_P_SKIP'
export const ME_GET_NOTIFICATION_P_LOADED = 'ME_GET_NOTIFICATION_P_LOADED'
export const ME_GET_NOTIFICATION_P_FINISHED = 'ME_GET_NOTIFICATION_P_FINISHED'


export const ME_GET_NOTIFICATIONS_OTHER = 'ME_GET_NOTIFICATIONS_OTHER'
export const ME_GET_NOTIFICATION_OT_SKIP = 'ME_GET_NOTIFICATION_OT_SKIP'
export const ME_GET_NOTIFICATION_OT_LOADED = 'ME_GET_NOTIFICATION_OT_LOADED'
export const ME_GET_NOTIFICATION_OT_FINISHED = 'ME_GET_NOTIFICATION_OT_FINISHED'

export const ME_GET_NOTIFICATION_TICKET = 'ME_GET_NOTIFICATION_TICKET'
export const ME_GET_NOTIFICATION_TICKET_SKIP = 'ME_GET_NOTIFICATION_TICKET_SKIP'
export const ME_GET_NOTIFICATION_TICKET_LOADED = 'ME_GET_NOTIFICATION_TICKET_LOADED'
export const ME_GET_NOTIFICATION_TICKET_FINISHED = 'ME_GET_NOTIFICATION_TICKET_FINISHED'

export const ME_GET_NOTIFICATION_ORDERNEW = 'ME_GET_NOTIFICATION_ORDERNEW'
export const ME_GET_NOTIFICATION_ORDERNEW_SKIP = 'ME_GET_NOTIFICATION_ORDERNEW_SKIP'
export const ME_GET_NOTIFICATION_ORDERNEW_LOADED = 'ME_GET_NOTIFICATION_ORDERNEW_LOADED'
export const ME_GET_NOTIFICATION_ORDERNEW_FINISHED = 'ME_GET_NOTIFICATION_ORDERNEW_FINISHED'

export const ME_GET_NOTIFICATION_NEWS = 'ME_GET_NOTIFICATION_NEWS'
export const ME_GET_NOTIFICATION_NEWS_SKIP = 'ME_GET_NOTIFICATION_NEWS_SKIP'
export const ME_GET_NOTIFICATION_NEWS_LOADED = 'ME_GET_NOTIFICATION_NEWS_LOADED'
export const ME_GET_NOTIFICATION_NEWS_FINISHED = 'ME_GET_NOTIFICATION_NEWS_FINISHED'

export const ME_GET_NOTIFICATION_COUNT = 'ME_GET_NOTIFICATION_COUNT'

export const ME_GET_ACTIVITY_NOTIFICATION_NO_READ = "ME_GET_ACTIVITY_NOTIFICATION_NO_READ"
export const ME_GET_PROMO_NOTIFICATION_NO_READ = "ME_GET_PROMO_NOTIFICATION_NO_READ"
export const ME_GET_OTHER_NOTIFICATION_NO_READ = "ME_GET_OTHER_NOTIFICATION_NO_READ"
export const ME_GET_TICKET_NOTIFICATION_NO_READ = "ME_GET_TICKET_NOTIFICATION_NO_READ"
export const ME_GET_ORDER_NOTIFICATION_NO_READ = "ME_GET_ORDER_NOTIFICATION_NO_READ"
export const ME_GET_NEWS_NOTIFICATION_NO_READ = "ME_GET_NEWS_NOTIFICATION_NO_READ"


export const ME_GET_WISH_PRODUCTS = 'ME_GET_WISH_PRODUCTS'
export const ME_GET_WISH_SKIP = 'ME_GET_WISH_SKIP'
export const ME_GET_REFRESH_PRODUCTS = 'ME_GET_REFRESH_PRODUCTS'

export const ME_GET_YOU_LIKE_PRODUCTS = 'ME_GET_YOU_LIKE_PRODUCTS'
export const ME_GET_YOU_LIKE_SKIP = 'ME_GET_YOU_LIKE_SKIP'

export const ME_CHANGE_PASSWORD = 'ME_CHANGE_PASSWORD'
export const ME_CHANGE_EMAIL = 'ME_CHANGE_EMAIL'
export const ME_UPDATE_ADDRESS = 'ME_UPDATE_ADDRESS'
export const ME_DELETE_ADDRESS = 'ME_DELETE_ADDRESS'
export const ME_ADD_ADDRESS = 'ME_ADD_ADDRESS'


export const ME_CHANGE_CURRENCY = 'ME_CHANGE_CURRENCY'


export const ME_ORDER_COUNT_PROCESSING = 'ME_ORDER_COUNT_PROCESSING'
export const ME_ORDER_COUNT_SHIPPED = 'ME_ORDER_COUNT_SHIPPED'
export const ME_ORDER_COUNT_CANCELED = 'ME_ORDER_COUNT_CANCELED'
export const ME_ORDER_COUNT_RECEIPT = 'ME_ORDER_COUNT_RECEIPT'
export const ME_ORDER_COUNT_UNPAID = 'ME_ORDER_COUNT_UNPAID'
export const ME_GET_MESSAGE = 'ME_GET_MESSAGE'
export const Me_GET_CREDITCARDS = 'Me_GET_CREDITCARDS'
export const Me_GET_MERCADOCREDITCARDS = 'Me_GET_MERCADOCREDITCARDS'
export const ME_DEL_CREDIT_CARD = 'ME_DEL_CREDIT_CARD'
export const ME_DEL_MERCADO_CARD = 'ME_DEL_MERCADO_CARD'
export const ME_REMOVE_EXPIRED_PRODUCTS = 'ME_REMOVE_EXPIRED_PRODUCTS'

export const ME_GET_TRACK_ORDER_MESSAGE = 'ME_GET_TRACK_ORDER_MESSAGE';
export const ME_TRACK_ORDER_SKIP = "ME_TRACK_ORDER_SKIP";

// points
export const ME_GET_POINTS_ALL = "ME_GET_POINTS_ALL";
export const ME_GET_POINTS_ALL_SKIP = "ME_GET_POINTS_ALL_SKIP";
export const ME_GET_POINTS_Recived = "ME_GET_POINTS_Recived";
export const ME_GET_POINTS_Recived_SKIP = "ME_GET_POINTS_Recived_SKIP";
export const ME_GET_POINTS_Used = "ME_GET_POINTS_Used";
export const ME_GET_POINTS_Used_SKIP = "ME_GET_POINTS_Used_SKIP";
export const ME_GET_POINTS_Expired = "ME_GET_POINTS_Expired";
export const ME_GET_POINTS_Expired_SKIP = "ME_GET_POINTS_Expired_SKIP";
export const ME_GET_POINTS_CUSTOMER_NUM = "ME_GET_POINTS_CUSTOMER_NUM";
export const ME_GET_POINTS_PRODUCTS = "ME_GET_POINTS_PRODUCTS";
export const ME_GET_POINTS_PRODUCT_SKIP = "ME_GET_POINTS_PRODUCT_SKIP";

export const ME_GET_NO_LOGIN = "ME_GET_NO_LOGIN";

export const CHANGE_GET_ME_DATA = "CHANGE_GET_ME_DATA";

export const GET_ME_CURRENCY_LIST = "GET_ME_CURRENCY_LIST";

export const GET_SHOPPING_CART_NUM = "GET_SHOPPING_CART_NUM";

export const GET_INDEX_MESSAGE_CODE_LOGIN = "GET_INDEX_MESSAGE_CODE_LOGIN";

export const GET_MY_PREFERENCES_MESSAGE_CODE = "GET_MY_PREFERENCES_MESSAGE_CODE";

export const GET_RELATION_PRODUCTS = "GET_RELATION_PRODUCTS";

export const GET_RELATION_PRODUCTS_SKIP = "GET_RELATION_PRODUCTS_SKIP";

// survey
export const GET_SURVEY_ANSWER = "GET_SURVEY_ANSWER";

export const GET_RECORD_WISHLIST_EVENT = "GET_RECORD_WISHLIST_EVENT";

export const GET_HAS_NO_COMMENT_ORDER = 'GET_HAS_NO_COMMENT_ORDER';

export const GET_DOBULE_POINTS_DATA = "GET_DOBULE_POINTS_DATA";

// points mall
export const ME_GET_POINTS_MALL_PRODUCTS = 'ME_GET_POINTS_MALL_PRODUCTS';
export const ME_GET_POINTS_MALL_PRODUCTS_SKIP = 'ME_GET_POINTS_MALL_PRODUCTS_SKIP';
export const ME_GET_POINTS_MALL_PRODUCTS_SKIP_CLEAR = 'ME_GET_POINTS_MALL_PRODUCTS_SKIP_CLEAR';
export const ME_GET_POINTS_MALL_PRODUCTS_CLEAR = 'ME_GET_POINTS_MALL_PRODUCTS_CLEAR';

export const CHANGE_ME_FEED_POINT_COUNT = "CHANGE_ME_FEED_POINT_COUNT";
