/**
 * Created by shao_ on 2017/8/23.
 */

export const ME_INITIALIZED = 'ME_INITIALIZED'
export const ME_GET = 'ME_GET'
export const ME_GET_FEED = 'ME_GET_FEED'
export const ME_GET_ADDRESSES = 'ME_GET_ADDRESSES'
export const ME_MAKE_DEFAULT = 'ME_MAKE_DEFAULT'
export const ME_GET_COUPONS = 'ME_GET_COUPONS'
export const ME_GET_CREDITS = 'ME_GET_CREDITS'
export const ME_GET_CREDITS_SKIP = 'ME_GET_CREDITS_SKIP'
export const ME_GET_YOU_LIKES = 'ME_GET_YOU_LIKES'
export const ME_GET_WISH_LIST = 'ME_GET_WISH_LIST'
export const ME_GET_NOTIFICATIONS_ORDER = 'ME_GET_NOTIFICATIONS_ORDER'
export const ME_GET_NOTIFICATIONS_PROMOTION = 'ME_GET_NOTIFICATIONS_PROMOTION'
export const ME_GET_NOTIFICATIONS_OTHER = 'ME_GET_NOTIFICATIONS_OTHER'
export const ME_GET_WISH_PRODUCTS = 'ME_GET_WISH_PRODUCTS'
export const ME_GET_WISH_SKIP = 'ME_GET_WISH_SKIP'