const state = {
    me: null,
    isLogin:false,
    addresses: [],
    coupons: [],
    feed: null,
/*    allPoints:[],*/
    credits: [],
    initialized: false,
    wishlist: null,
    save:[],
    orderNotifications: [],
    promotionNotifications: [],
    otherNotifications: [],
    ticketNotifications: [],
    orderNewNotifications: [],
    newsNotifications: [],

    activityNotificationnoRead: 0,
    promoNotificationnoRead: 0,
    otherNotificationnoRead: 0,
    ticketNotificationnoRead: 0,
    orderNotificationnoRead: 0,
    newsNotificationnoRead: 0,
    wishProducts: [],
    refreshProducts:[],
    wishskip: 0,
    youlikeProducts:[],
    youlikeskip:0,
    creditskip: 0,
    headerImage: null,
    promotionNtSkip: 0,
    promotionNtLoaded: false,
    promotionNtFinished: false,
    orderNtSkip: 0,
    orderNtLoaded: false,
    orderNtFinished: false,
    otherNtSkip: 0,
    otherNtLoaded: false,
    otherNtFinished: false,
    ticketNtSkip: 0,
    ticketNtLoaded: false,
    ticketNtFinished: false,
    orderNewNtSkip: 0,
    orderNewNtLoaded: false,
    orderNewNtFinished: false,
    newsNtSkip: 0,
    newsNtLoaded: false,
    newsNtFinished: false,
    notificationCount: 0,
    orderCountProcessing: 0,
    orderCountShipped: 0,
    orderCountReceipt: 0,
    orderCountCanceled: 0,
    orderCountUnpaid: 0,
    message:[],
    creditcards:[],
    mercadocreditcards:[],
    trackOrder:[],
    trackOrderSkip:0,
    expiredCoupons:[],
    expiredCouponsSkip:0,
    currencyList:[],
    shoppingCartCount:0,
    messageM1518:"",
    messageM1521:null,
    relationProducts:[],
    relationProductsSkip:0,
    survey: {},
    wishlistEvent:{"requestId":"","experimentId":""},
    hasNoCommentOrder: false,
    dobulePoints:null,
    vipShow:false
}

export default state;