const state = {
    me: null,
    isLogin:false,
    addresses: [],
    coupons: [],
    feed: null,
/*    allPoints:[],*/
    credits: [],
    initialized: false,
    wishlist: null,
    save:[],
    orderNotifications: [],
    promotionNotifications: [],
    otherNotifications: [],
    wishProducts: [],
    refreshProducts:[],
    wishskip: 0,
    youlikeProducts:[],
    youlikeskip:0,
    creditskip: 0,
    headerImage: null,
    promotionNtSkip: 0,
    promotionNtLoaded: false,
    promotionNtFinished: false,
    orderNtSkip: 0,
    orderNtLoaded: false,
    orderNtFinished: false,
    otherNtSkip: 0,
    otherNtLoaded: false,
    otherNtFinished: false,
    notificationCount: 0,
    orderCountProcessing: 0,
    orderCountShipped: 0,
    orderCountReceipt: 0,
    orderCountCanceled: 0,
    orderCountUnpaid: 0,
    message:[],
    creditcards:[],
    mercadocreditcards:[],
    trackOrder:[],
    trackOrderSkip:0,
    expiredCoupons:[],
    expiredCouponsSkip:0,
    currencyList:[],
    shoppingCartCount:0,
    messageM1518:"",
    messageM1521:null
}

export default state;