export const ME_GET = 'ME_GET'
export const INIT_ME = 'INIT_ME'

export const ME_ORDER_COUNT_ALL = 'ME_ORDER_COUNT_ALL'
export const ME_ORDER_COUNT_PROCESSING = 'ME_ORDER_COUNT_PROCESSING'
export const ME_ORDER_COUNT_SHIPPED = 'ME_ORDER_COUNT_SHIPPED'
export const ME_ORDER_COUNT_CANCELED = 'ME_ORDER_COUNT_CANCELED'
export const ME_ORDER_COUNT_RECEIPT = 'ME_ORDER_COUNT_RECEIPT'
export const ME_ORDER_COUNT_UNPAID = 'ME_ORDER_COUNT_UNPAID'
export const ME_ORDER_COUNT_PAID = 'ME_ORDER_COUNT_PAID'

export const HOME_ORDERS_ALL = 'HOME_ORDERS_ALL'
export const ME_ORDER_DETAIL = 'ME_ORDER_DETAIL'
export const HOME_LOADING_ALL = 'HOME_LOADING_ALL'
export const HOME_ORDER_ALL_SKIP = 'HOME_ORDER_ALL_SKIP'
export const HOME_ALL_DONE = 'HOME_ALL_DONE'

export const HOME_ORDERS_PROCESSING = 'HOME_ORDERS_PROCESSING'
export const HOME_LOADING_PROCESSING = 'HOME_LOADING_PROCESSING'
export const HOME_ORDER_PROCESSING_SKIP = 'HOME_ORDER_PROCESSING_SKIP'
export const HOME_PROCESSING_DONE = 'HOME_PROCESSING_DONE'

export const HOME_ORDERS_UNPAID = 'HOME_ORDERS_UNPAID'
export const HOME_LOADING_UNPAID = 'HOME_LOADING_UNPAID'
export const HOME_ORDER_UNPAID_SKIP = 'HOME_ORDER_UNPAID_SKIP'
export const HOME_UNPAID_DONE = 'HOME_UNPAID_DONE'

export const HOME_ORDERS_PAID = 'HOME_ORDERS_PAID'
export const HOME_LOADING_PAID = 'HOME_LOADING_PAID'
export const HOME_ORDER_PAID_SKIP = 'HOME_ORDER_PAID_SKIP'
export const HOME_PAID_DONE = 'HOME_PAID_DONE'

export const HOME_ORDERS_SHIPPED = 'HOME_ORDERS_SHIPPED'
export const HOME_LOADING_SHIPPED = 'HOME_LOADING_SHIPPED'
export const HOME_ORDER_SHIPPED_SKIP = 'HOME_ORDER_SHIPPED_SKIP'
export const HOME_SHIPPED_DONE = 'HOME_SHIPPED_DONE'

export const HOME_ORDERS_CONFIRMED = 'HOME_ORDERS_CONFIRMED'
export const HOME_LOADING_CONFIRMED = 'HOME_LOADING_CONFIRMED'
export const HOME_ORDER_CONFIRMED_SKIP = 'HOME_ORDER_CONFIRMED_SKIP'
export const HOME_CONFIRMED_DONE = 'HOME_CONFIRMED_DONE'

export const HOME_ORDERS_CANCELED = 'HOME_ORDERS_CANCELED'
export const HOME_LOADING_CANCELED = 'HOME_LOADING_CANCELED'
export const HOME_ORDER_CANCELED_SKIP = 'HOME_ORDER_CANCELED_SKIP'
export const HOME_CANCELED_DONE = 'HOME_CANCELED_DONE'

export const HOME_ORDERS_STATUS_UPDATE = 'HOME_ORDERS_STATUS_UPDATE'
export const HOME_CHANGE_TAB = 'HOME_CHANGE_TAB'
export const DETAIL_LOAD_ORDER = 'DETAIL_LOAD_ORDER'
export const DETAIL_CONFIRM_ORDER = 'DETAIL_CONFIRM_ORDER'
export const DETAIL_CANCEL_ORDER = 'DETAIL_CANCEL_ORDER'
export const DETAIL_LOAD_LAST_REPLY = 'DETAIL_LOAD_LAST_REPLY'

export const HOME_ORDER_ID = 'HOME_ORDER_ID'

export const ME_COUPONS = 'ME_COUPONS'
export const ME_GET_CREDITS = 'ME_GET_CREDITS'
export const ME_GET_MESSAGE = 'ME_GET_MESSAGE'
export const ME_GET_WISH_PRODUCTS = 'ME_GET_WISH_PRODUCTS'
export const ME_GET_WISH_SKIP = 'ME_GET_WISH_SKIP'
export const ME_GET_CREDITCARDS = 'Me_GET_CREDITCARDS'
export const ME_GET_MERCADOCREDITCARDS = 'ME_GET_MERCADOCREDITCARDS'

export const ME_GET_ADDRESSES = 'ME_GET_ADDRESSES'
export const ME_DELETE_ADDRESS = 'ME_DELETE_ADDRESS'
export const GLOBAL_GET_COUNTRIES = 'GLOBAL_GET_COUNTRIES'
export const GLOBAL_GET_STATES = 'GLOBAL_GET_STATES'
export const GLOBAL_GET_CURRENCIES = 'GLOBAL_GET_CURRENCIES'
export const ME_UPDATE_ADDRESS = 'ME_UPDATE_ADDRESS'
export const ME_ADD_ADDRESS = 'ME_ADD_ADDRESS'

export const ME_CHANGE_EMAIL = 'ME_CHANGE_EMAIL'
export const ME_HEADER_IMAGE = 'ME_HEADER_IMAGE'

export const ME_SHARE_KEY = 'ME_SHARE_KEY'
export const ME_COPY_LINK = 'ME_COPY_LINK'

export const REVIEW_LOAD_COMMENT = 'REVIEW_LOAD_COMMENT'
export const REVIEW_SEND_COMMENT = 'REVIEW_SEND_COMMENT'
export const REVIEW_SENDING = 'REVIEW_SENDING'

export const GLOBAL_GET_TICKETS = 'GLOBAL_GET_TICKETS'
export const HOME_GET_M1135 = 'HOME_GET_M1135'
export const GLOBAL_GET_TICKET = 'GLOBAL_GET_TICKET'
export const GLOBAL_GET_TICKET_CON = 'GLOBAL_GET_TICKET_CON'
export const GLOBAL_GET_TICKET_ID = 'GLOBAL_GET_TICKET_ID'
export const GLOBAL_GET_TICKET_SUB = 'GLOBAL_GET_TICKET_SUB'

export const ME_SHARE_URL = 'ME_SHARE_URL'
export const GLOBAL_GET_LOGISTICS = 'GLOBAL_GET_LOGISTICS'
export const GLOBAL_GET_PACKAGE_LOGISTICS = 'GLOBAL_GET_PACKAGE_LOGISTICS'

export const GLOBAL_CANCEL_REASONS ='GLOBAL_CANCEL_REASONS'

export const ME_GET_NOTIFICATIONS_ORDER = 'ME_GET_NOTIFICATIONS_ORDER'
export const ME_GET_NOTIFICATION_O_SKIP = 'ME_GET_NOTIFICATION_O_SKIP'
export const ME_GET_NOTIFICATION_O_LOADED = 'ME_GET_NOTIFICATION_O_LOADED'
export const ME_GET_NOTIFICATION_O_FINISHED = 'ME_GET_NOTIFICATION_O_FINISHED'


export const ME_GET_NOTIFICATIONS_PROMOTION = 'ME_GET_NOTIFICATIONS_PROMOTION'
export const ME_GET_NOTIFICATION_P_SKIP = 'ME_GET_NOTIFICATION_P_SKIP'
export const ME_GET_NOTIFICATION_P_LOADED = 'ME_GET_NOTIFICATION_P_LOADED'
export const ME_GET_NOTIFICATION_P_FINISHED = 'ME_GET_NOTIFICATION_P_FINISHED'


export const ME_GET_NOTIFICATIONS_OTHER = 'ME_GET_NOTIFICATIONS_OTHER'
export const ME_GET_NOTIFICATION_OT_SKIP = 'ME_GET_NOTIFICATION_OT_SKIP'
export const ME_GET_NOTIFICATION_OT_LOADED = 'ME_GET_NOTIFICATION_OT_LOADED'
export const ME_GET_NOTIFICATION_OT_FINISHED = 'ME_GET_NOTIFICATION_OT_FINISHED'

export const ME_GET_NOTIFICATION_COUNT = 'ME_GET_NOTIFICATION_COUNT'

export const ME_GET_FEED_SUMMARY = 'ME_GET_FEED_SUMMARY'
export const GLOBAL_GET_RETURNLABEL = 'GLOBAL_GET_RETURNLABEL'