/**
 * Created by shao_ on 2017/9/4.
 */

export const GLOBAL_LOGOUT = 'GLOBAL_LOGOUT'

export const GLOBAL_PAGING = 'GLOBAL_PAGING'
export const GLOBAL_SCREEN_LOADING = 'GLOBAL_SCREEN_LOADING'


export const GLOBAL_GET_COUNTRIES = 'GLOBAL_GET_COUNTRIES'
export const GLOBAL_GET_STATES = 'GLOBAL_GET_STATES'

export const GLOBAL_GET_CURRENCIES = 'GLOBAL_GET_CURRENCIES'

export const GLOBAL_LIKE = 'GLOBAL_LIKE'
export const GLOBAL_UN_LIKE = 'GLOBAL_UN_LIKE'