/**
 * Created by shao_ on 2017/9/4.
 */

export const GLOBAL_LOGOUT = 'GLOBAL_LOGOUT'

export const GLOBAL_PAGING = 'GLOBAL_PAGING'
export const GLOBAL_SCREEN_LOADING = 'GLOBAL_SCREEN_LOADING'


export const GLOBAL_GET_COUNTRIES = 'GLOBAL_GET_COUNTRIES'
export const GLOBAL_GET_STATES = 'GLOBAL_GET_STATES'

export const GLOBAL_GET_CURRENCIES = 'GLOBAL_GET_CURRENCIES'

export const GLOBAL_LIKE = 'GLOBAL_LIKE'
export const GLOBAL_UN_LIKE = 'GLOBAL_UN_LIKE'
export const GLOBAL_CANCEL_SAVE = 'GLOBAL_CANCEL_SAVE'
export const GLOBAL_CLEAR_ID = 'GLOBAL_CLEAR_ID'

export const APP_CONFIRM_SHOW = "APP_CONFIRM_SHOW";

export const GET_PRODUCT_DETAIL_MESSAGE = "GET_PRODUCT_DETAIL_MESSAGE";

export const GET_PRODUCT_DETAIL_MESSAGE_PRODUCT_ID = "GET_PRODUCT_DETAIL_MESSAGE_PRODUCT_ID";

export const ADD_TO_CART_IS_SHOW = "ADD_TO_CART_IS_SHOW";

export const GLOBAL_LOADING_SHOW = "GLOBAL_LOADING_SHOW";